--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Eric-pm-pl/NoFarmlandDecay
build-by-default: true
branches:
- pm4
- pm5
projects:
  NoFarmlandDecay:
    path: ""
    icon: icon.png
...
